export const envExample = {
  NODE_ENV: 'development',
  PORT: 3000,
  WHATSAPP_VERIFY_TOKEN: '',
  WHATSAPP_ACCESS_TOKEN: '',
  WHATSAPP_PHONE_NUMBER_ID: '',
  WHATSAPP_BUSINESS_ACCOUNT_ID: '',
  WHATSAPP_APP_ID: '',
  WHATSAPP_APP_SECRET: '',
  WHATSAPP_API_VERSION: 'v23.0',
};
